# 181219

# 회귀분석

- 비선형을 선형으로
- 돈과 관련된 것은 log를 취하여 직선화시켜야함(선형관계로 바꾸기)
- 비선형인 데이터들은 변환을 통하여 선형관계로 바꾼 후 회귀분석을 실시하여야 한다.

In [1]:
import numpy as np 
import pandas as pd #기초 함수 불러오기

x = np.random.randn(3) #랜덤한 숫자 3개 뽑아내기
x


array([-0.00890271,  0.75298164,  0.10603663])

In [2]:
y=x*100+10
# w=100(기울기), b=10(절편)이라고 할 때 이 값을 컴퓨터가 찾아낼 수 있는가?
y

array([ 9.10972886, 85.29816428, 20.60366282])

In [3]:
lr=1.0 # 시스템마다의 학습 속도(예를들어 엑셀을 밟는 정도, 시스템마다 반응 속도가 다르기때문에 최적의 lr을 찾아야 함)
w=np.random.rand() 
b=np.random.rand()
w,b
# w와 b에 초기값을 지정 한 후 이제 학습을 통해 컴퓨터가 w와 b를 찾아낼 수 있는지 보자
# 내가 예측한 값이 실제 값과 얼마나 차이가 있는지 보고 그 차이(error)를 줄여가면서 w와 b를 찾는다.

(0.27567640355191225, 0.7952567381337595)

In [4]:
n_epoch=300 
for epoch in range(n_epoch): #300번 돌려볼것이다
    y_pred = w*x + b
    error = np.abs(y - y_pred).mean() #이 error가 작으면 작을수록 좋은 것
    
    if error < 0.01:
        break # error가 0.01보다 작으면 for문을 빠져나온다 = 최적화시킨다
        
    w = w - lr*((y_pred-y)*x).mean() # abs는 절댓값 x를 곱해주기때문에 오류의 변환은 x에 영향을 미친다.
    # 뮤는 lr Grad는 기울기 : (y_pred-y)*x mean은 x를 3개로 받았기 때문에 그 평균값을 곱해줌
    b = b - lr*(y_pred-y).mean() # b는 절편이기 때문에 x를 곱해주지 않음
    if epoch%10 ==0: 
        print('epoch=', epoch, 'error=', error, 'w=',w,'b=',b) # epoch, error, w, b를 출력한다

print('--------------------------------------------------------------------------------')    
print('epoch=', epoch, 'error=', error, 'w=',w,'b=',b) # epoch, error, w, b를 출력한다

# 처음에 x(3개의 랜덤한 수)만 주어졌는데 컴퓨터가 학습을 통해 오차(error)를 줄여나가면서 w와 b가 100과 10임을 찾아냈음

epoch= 0 error= 37.46380964846916 w= 22.10771257543128 b= 38.25906638660292
epoch= 10 error= 9.592191862338767 w= 73.44608199605288 b= 18.39077428848861
epoch= 20 error= 3.2266411789030656 w= 91.06773858158867 b= 12.822505870336903
epoch= 30 error= 1.0853841798054524 w= 96.99534757790262 b= 10.949440315552275
epoch= 40 error= 0.3651037572676283 w= 98.98928885365947 b= 10.319374681296383
epoch= 50 error= 0.12281435094698818 w= 99.66001491093472 b= 10.107431910550195
epoch= 60 error= 0.04131254334770892 w= 99.88563511819846 b= 10.036138166487138
epoch= 70 error= 0.013896798091563412 w= 99.96152970641907 b= 10.012156230587022
--------------------------------------------------------------------------------
epoch= 74 error= 0.008987685637555032 w= 99.97225559949464 b= 10.008766954931914


# 선형회귀 핵심 코드 정리

In [5]:
import numpy as np 
import pandas as pd #기초 함수 불러오기
x = np.random.randn(3) #랜덤한 숫자 3개 뽑아내기

In [6]:
y=x*100+10

lr=1.0 # 시스템마다의 학습 속도(예를들어 엑셀을 밟는 정도, 시스템마다 반응 속도가 다르기때문에 최적의 lr을 찾아야 함)
w=np.random.rand()
b=np.random.rand()

n_epoch=300 
for epoch in range(n_epoch): #300번 돌려볼것이다
    y_pred = w*x + b
    error = np.abs(y - y_pred).mean() #이 error가 작으면 작을수록 좋은 것
    
    if error < 0.01:
        break # error가 0.01보다 작으면 for문을 빠져나온다 = 최적화시킨다
        
    w = w - lr*((y_pred-y)*x).mean() # abs는 절댓값 x를 곱해주기때문에 오류의 변환은 x에 영향을 미친다.
    b = b - lr*(y_pred-y).mean() # b는 절편이기 때문에 x를 곱해주지 않음
    
    if epoch%10 ==0:
        print('epoch=', epoch, 'error=', error, 'w=',w,'b=',b) # epoch, error, w, b를 출력한다

print('--------------------------------------------------------------------------------')    
print('epoch=', epoch, 'error=', error, 'w=',w,'b=',b) # epoch, error, w, b를 출력한다

# 처음에 x(3개의 랜덤한 수)만 주어졌는데 컴퓨터가 학습을 통해 오차(error)를 줄여나가면서 w와 b가 100과 10임을 찾아냈음

epoch= 0 error= 110.3171367517034 w= 130.84035407276465 b= -21.167146157138905
epoch= 10 error= 0.1575758289570075 w= 100.06198638227983 b= 9.96311320554625
--------------------------------------------------------------------------------
epoch= 15 error= 0.006496157486149438 w= 100.00483541716676 b= 9.997122596620022


# 연습

In [7]:
import numpy as np 
import pandas as pd
x = np.random.randn(5)

In [8]:
y=x*200+30

lr=1.0 # 시스템마다의 학습 속도(예를들어 엑셀을 밟는 정도, 시스템마다 반응 속도가 다르기때문에 최적의 lr을 찾아야 함)
w=np.random.rand()
b=np.random.rand()

n_epoch=500 
for epoch in range(n_epoch): #500번 돌려볼것이다
    y_pred = w*x + b
    error = np.abs(y - y_pred).mean() #이 error가 작으면 작을수록 좋은 것
    
    if error < 0.01:
        break # error가 0.01보다 작으면 for문을 빠져나온다 = 최적화시킨다
        
    w = w - lr*((y_pred-y)*x).mean() # abs는 절댓값 x를 곱해주기때문에 오류의 변환은 x에 영향을 미친다.
    b = b - lr*(y_pred-y).mean() # b는 절편이기 때문에 x를 곱해주지 않음
    
    if epoch%10 ==0:
        print('epoch=', epoch, 'error=', error, 'w=',w,'b=',b) # epoch, error, w, b를 출력한다

print('--------------------------------------------------------------------------------')    
print('epoch=', epoch, 'error=', error, 'w=',w,'b=',b) # epoch, error, w, b를 출력한다


epoch= 0 error= 125.07214477415837 w= 103.4419859528827 b= -45.375039658167175
epoch= 10 error= 1.2942917647668508 w= 198.59654808241646 b= 29.18279546689413
epoch= 20 error= 0.017318600361238622 w= 199.9812207040001 b= 29.989065226224977
--------------------------------------------------------------------------------
epoch= 22 error= 0.007308176139926559 w= 199.98780091057006 b= 29.992896736749042


# 변수가 2개일 때

In [9]:
import numpy as np 
import pandas as pd #기초 함수 불러오기
x1 = np.random.rand(100) #랜덤한 숫자 3개 뽑아내기 randn은 마이너스 값도 나오고 rand는 0에서 1사이의 값만 나옴
x2 = np.random.rand(100) #랜덤한 숫자 3개 뽑아내기

y=x1*10+x2*100+1000
print(x1)
print(x2)
print(y)

# w1=10 w2=100 b=1000


[0.67735573 0.74689755 0.81466074 0.60748271 0.05145446 0.47278255
 0.88048539 0.99794423 0.9989533  0.64676847 0.0105295  0.03284214
 0.84716956 0.34581733 0.50403173 0.05632962 0.09662219 0.44696693
 0.471957   0.30779443 0.04007789 0.49049445 0.1636966  0.65547513
 0.71088642 0.92326838 0.33740811 0.27980673 0.4780938  0.09865691
 0.88797503 0.37827725 0.59087444 0.99204789 0.72433351 0.51060087
 0.33819126 0.40456414 0.69061854 0.07435302 0.81650775 0.07193304
 0.60863548 0.78228007 0.18806615 0.63242547 0.77516714 0.02117351
 0.53805012 0.95799626 0.87853807 0.10952122 0.5640138  0.41905158
 0.47794255 0.80990561 0.7251933  0.6561499  0.33436545 0.12382218
 0.17710484 0.69544246 0.67682581 0.17544973 0.21694289 0.56783814
 0.92472094 0.0686812  0.55407051 0.97226353 0.28160851 0.92855679
 0.89762451 0.52122041 0.15862575 0.14686714 0.90248766 0.9907654
 0.00473688 0.63946214 0.96502233 0.51201855 0.48259573 0.9921929
 0.03566013 0.52251789 0.29341165 0.06125572 0.5189335  0.953817

In [10]:

lr=1.18 # 시스템마다의 학습 속도(예를들어 엑셀을 밟는 정도, 시스템마다 반응 속도가 다르기때문에 최적의 lr을 찾아야 함)
w1=np.random.rand()
w2=np.random.rand()
b=np.random.rand()

n_epoch=3000
for epoch in range(n_epoch): #300번 돌려볼것이다
    y_pred = w1*x1 + w2*x2 + b
    error = np.abs(y - y_pred).mean() #이 error가 작으면 작을수록 좋은 것
    
    if error < 0.01:
        break # error가 0.01보다 작으면 for문을 빠져나온다 = 최적화시킨다
        
    w1 = w1 - lr*((y_pred-y)*x1).mean() # abs는 절댓값 x를 곱해주기때문에 오류의 변환은 x에 영향을 미친다.
    w2 = w2 - lr*((y_pred-y)*x2).mean() # abs는 절댓값 x를 곱해주기때문에 오류의 변환은 x에 영향을 미친다.
    b = b - lr*(y_pred-y).mean() # b는 절편이기 때문에 x를 곱해주지 않음
    
    if epoch%50 ==0:
        print('epoch=', epoch, 'error=', error, 'w1=',w1, 'w2=',w2,'b=',b) # epoch, error, w, b를 출력한다

print('--------------------------------------------------------------------------------')    
print('epoch=', epoch, 'error=', error, 'w1=',w1, 'w2=',w2,'b=',b) # epoch, error, w, b를 출력한다

# 처음에 x(3개의 랜덤한 수)만 주어졌는데 컴퓨터가 학습을 통해 오차(error)를 줄여나가면서 w와 b가 100과 10임을 찾아냈음

epoch= 0 error= 1052.0459328970285 w1= 655.5592984875444 w2= 605.0122109241972 b= 1241.9408646384543
epoch= 50 error= 2.1730193422920796 w1= 15.505985631898955 w2= 105.7579095543136 b= 993.9991148916948
epoch= 100 error= 0.043957553878467476 w1= 10.103751823587741 w2= 100.12221365221596 b= 999.8792377678363
--------------------------------------------------------------------------------
epoch= 119 error= 0.009983890780972615 w1= 10.025210951450061 w2= 100.03018851927175 b= 999.9704047415725


# 더 복잡한 데이터(y값에 랜덤노이즈 추가)

In [11]:
import numpy as np 
import pandas as pd #기초 함수 불러오기
n=100
x1 = np.random.rand(n) #랜덤한 숫자 3개 뽑아내기 randn은 마이너스 값도 나오고 rand는 0에서 1사이의 값만 나옴
x2 = np.random.rand(n) #랜덤한 숫자 3개 뽑아내기

y=x1*30+x2*40+50
#y=y_1+np.random.randn(n)*0.1 #y에 표준편차가 1이 되는 랜덤넘버를 5개 섞었음(노이즈를 섞었음), 노이즈가 너무 커져서 0.1을 곱함

# w1=10 w2=100 b=1000
#x1,x2,y_1,y

In [12]:

lr=1.0 # 시스템마다의 학습 속도(예를들어 엑셀을 밟는 정도, 시스템마다 반응 속도가 다르기때문에 최적의 lr을 찾아야 함)
w1=np.random.rand()
w2=np.random.rand()
b=np.random.rand()

n_epoch=30000
for epoch in range(n_epoch): #300번 돌려볼것이다
    y_pred = w1*x1 + w2*x2 + b
    error = np.abs(y - y_pred).mean() #이 error가 작으면 작을수록 좋은 것
    
    if error < 0.1:
        break # error가 0.01보다 작으면 for문을 빠져나온다 = 최적화시킨다
        
    w1 = w1 - lr*((y_pred-y)*x1).mean() # abs는 절댓값 x를 곱해주기때문에 오류의 변환은 x에 영향을 미친다.
    w2 = w2 - lr*((y_pred-y)*x2).mean() # abs는 절댓값 x를 곱해주기때문에 오류의 변환은 x에 영향을 미친다.
    b = b - lr*(y_pred-y).mean() # b는 절편이기 때문에 x를 곱해주지 않음
    
    if epoch%50 ==0:
        print('epoch=', epoch, 'error=', error, 'w1=',w1, 'w2=',w2,'b=',b) # epoch, error, w, b를 출력한다

print('--------------------------------------------------------------------------------')    
print('epoch=', epoch, 'error=', error, 'w1=',w1, 'w2=',w2,'b=',b) # epoch, error, w, b를 출력한다

# 처음에 x(3개의 랜덤한 수)만 주어졌는데 컴퓨터가 학습을 통해 오차(error)를 줄여나가면서 w와 b가 100과 10임을 찾아냈음

epoch= 0 error= 88.13939198377429 w1= 52.23402705172744 w2= 50.95607584739625 b= 88.19353999063172
--------------------------------------------------------------------------------
epoch= 50 error= 0.09851343248453957 w1= 29.832986735612295 w2= 39.62179542730899 b= 50.313350121110645


# LinearRegression : 모델선택(생성자)

In [13]:
from sklearn.linear_model import LinearRegression
x1 = np.random.rand(n) #랜덤한 숫자 3개 뽑아내기 randn은 마이너스 값도 나오고 rand는 0에서 1사이의 값만 나옴
x2 = np.random.rand(n) #랜덤한 숫자 3개 뽑아내기
x3 = np.random.rand(n)

y=x1*30+x2*40+x3*50+60

In [14]:
X=pd.DataFrame(x1)
X[1]=x2
X[2]=x3
X

0         1         2
0   0.094301  0.937322  0.842636
1   0.215226  0.238455  0.220160
2   0.292336  0.991086  0.880039
3   0.012838  0.074795  0.298353
4   0.377578  0.246334  0.554775
5   0.399473  0.147533  0.052983
6   0.464674  0.389494  0.524744
7   0.407680  0.883540  0.526845
8   0.331265  0.447370  0.845254
9   0.214493  0.795344  0.234992
10  0.140831  0.102725  0.594712
11  0.595302  0.206049  0.298602
12  0.297851  0.726928  0.432167
13  0.832264  0.130924  0.118782
14  0.527048  0.270538  0.113217
15  0.785679  0.710625  0.265251
16  0.965037  0.862862  0.666804
17  0.629676  0.919847  0.438085
18  0.773780  0.353225  0.906392
19  0.865539  0.561247  0.945923
20  0.928844  0.802199  0.017841
21  0.718272  0.837637  0.953026
22  0.923696  0.989138  0.788582
23  0.866656  0.263773  0.749947
24  0.706993  0.591170  0.713830
25  0.605929  0.461464  0.050284
26  0.395389  0.099718  0.091661
27  0.277704  0.949193  0.896967
28  0.421415  0.113945  0.273236
29  0.479130  0.840700  0.197294
..       ...       ...       ...
70  0.548682  0.051173  0.276786
71  0.451508  0.677543  0.695287
72  0.167460  0.844674  0.591366
73  0.807146  0.431832  0.456767
74  0.129086  0.281931  0.134738
75  0.773247  0.707094  0.456329
76  0.789979  0.635787  0.939679
77  0.220733  0.926875  0.551321
78  0.568044  0.449876  0.117863
79  0.902055  0.083446  0.830989
80  0.172579  0.091191  0.256712
81  0.076587  0.537737  0.373541
82  0.253102  0.133257  0.829227
83  0.794277  0.323511  0.597073
84  0.336673  0.000771  0.539995
85  0.522194  0.316034  0.714666
86  0.677354  0.126425  0.981517
87  0.961634  0.735269  0.329409
88  0.812636  0.191738  0.529006
89  0.674616  0.123708  0.757845
90  0.778196  0.880669  0.735202
91  0.294980  0.890748  0.153216
92  0.922368  0.653574  0.054387
93  0.879744  0.789052  0.647332
94  0.062114  0.316756  0.566473
95  0.648889  0.637452  0.561398
96  0.435513  0.343864  0.786436
97  0.573023  0.078036  0.986558
98  0.852415  0.560039  0.294566
99  0.154564  0.890871  0.605978

[100 rows x 3 columns]

In [15]:
model= LinearRegression() # 모델 선택(생성자)

## fit : 모델 학습

In [16]:
model.fit(X,y) # 모델 학습

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [17]:
X.shape

(100, 3)

In [18]:
model.coef_

array([30., 40., 50.])

In [19]:
model.intercept_

60.000000000000014

# Prediction : 모델을 이용한 예측

In [20]:
new_X=[1,1,2]
model.predict([new_X]) #2차원구조를 원하기때문에 기본적으로 꺽새두개가 필요함 [[]] 예) model.predict([[1,1,1]])

array([230.])

In [21]:
z=np.random.rand(10,3)
z

array([[0.37806595, 0.37494747, 0.28685045],
       [0.39523574, 0.21674646, 0.00462743],
       [0.60033103, 0.19010427, 0.38887803],
       [0.04801821, 0.05485128, 0.6078559 ],
       [0.79808347, 0.1418487 , 0.64331893],
       [0.24271826, 0.11828387, 0.03851056],
       [0.33234865, 0.35921543, 0.11686525],
       [0.2128398 , 0.53570701, 0.12631761],
       [0.05383652, 0.81804293, 0.44235194],
       [0.34757274, 0.07714373, 0.56784203]])

In [22]:
model.predict(z) #회귀식에 값을 넣은 예측값

array([100.68239945,  80.75830224, 105.05800318,  94.02739231,
       121.78239847,  73.9384308 ,  90.18233878,  94.12935518,
       116.45441009, 101.90503286])

## DataFrame이란?

In [23]:
zz=np.random.randn(100,3)
zz


array([[ 1.41173958e+00, -1.30211049e-01, -1.32917782e+00],
       [ 5.25604852e-01, -1.11923406e-01, -1.43303295e+00],
       [-9.78507285e-01, -1.44599674e+00,  4.83988925e-01],
       [ 8.69870831e-01, -9.13993251e-01, -2.76701680e-01],
       [-1.82119046e-01,  8.91626215e-01, -5.32590155e-01],
       [-6.11629377e-01, -2.31683089e-01, -2.95687271e+00],
       [-7.15502298e-02,  1.45220606e+00, -1.13332010e+00],
       [ 7.50211454e-01,  9.95696016e-01,  1.74277727e-01],
       [ 4.01753292e-01, -2.17852381e-01,  1.93656760e+00],
       [-2.19441091e+00, -9.02095178e-02,  4.65955137e-01],
       [-1.48104954e+00, -6.08569949e-01,  2.51965570e+00],
       [ 1.14321047e+00, -1.26964783e+00,  9.25998779e-01],
       [-2.01283831e+00,  1.06296560e+00,  5.91071475e-01],
       [ 1.11603615e+00, -1.48486718e+00, -7.13075093e-01],
       [-1.15249428e+00,  1.60831705e+00,  9.07566989e-01],
       [ 2.58201602e-01, -1.11959371e+00, -4.41694278e-01],
       [-9.31500232e-01,  6.60178584e-01

In [24]:
type(zz)

numpy.ndarray

In [25]:
z_d=pd.DataFrame(zz)
z_d 
#데이터프레임이란 테이블처럼 보기좋게 깔끔하게 보여지는 것이고, 자동으로 인덱스가 생성된다

0         1         2
0   1.411740 -0.130211 -1.329178
1   0.525605 -0.111923 -1.433033
2  -0.978507 -1.445997  0.483989
3   0.869871 -0.913993 -0.276702
4  -0.182119  0.891626 -0.532590
5  -0.611629 -0.231683 -2.956873
6  -0.071550  1.452206 -1.133320
7   0.750211  0.995696  0.174278
8   0.401753 -0.217852  1.936568
9  -2.194411 -0.090210  0.465955
10 -1.481050 -0.608570  2.519656
11  1.143210 -1.269648  0.925999
12 -2.012838  1.062966  0.591071
13  1.116036 -1.484867 -0.713075
14 -1.152494  1.608317  0.907567
15  0.258202 -1.119594 -0.441694
16 -0.931500  0.660179  0.073826
17 -2.053334 -0.410009  0.984983
18  0.373615 -0.316457 -0.910265
19  1.820549 -0.829370 -1.223403
20 -0.993763  0.885741 -0.183402
21  1.230102  0.557161 -0.870269
22 -0.482104  1.544416 -0.751214
23  0.000725  0.913767 -1.174119
24 -0.765827  1.473470  0.604185
25 -0.176829 -0.398759  0.694766
26  0.304272 -1.611762 -0.329838
27 -0.204493  0.615394  1.788268
28  1.259765 -0.017751 -0.021037
29 -1.720902  1.020804 -0.348365
..       ...       ...       ...
70 -0.550595  0.765441  0.681132
71 -1.787954  0.581008 -0.223398
72  0.812592 -0.138479 -0.612797
73  1.019425 -0.487577  1.073828
74  2.206837  0.141871  1.284577
75  1.193384 -0.306242 -1.523471
76 -0.272826 -0.417777  0.547836
77 -1.604121 -1.256184  2.569916
78 -0.384150  2.460247 -0.018918
79  0.838264 -1.747767  1.660045
80 -0.193846 -0.170417 -0.328435
81  1.637230  0.716873  0.211344
82  0.395045  0.377992  0.747429
83 -0.398206 -0.418691 -0.804333
84 -0.077200 -0.317087 -0.561074
85 -2.877151 -0.703509  1.060913
86 -0.369436  0.857172  0.412655
87  0.203863 -1.000058  0.263256
88 -0.582854  1.437751  3.675889
89 -1.198611 -0.569169 -0.668428
90  0.880245  0.439989  0.717205
91 -0.572627  0.790528 -0.896259
92  0.822433 -0.308171 -0.610190
93 -0.690091 -0.801368 -0.797142
94 -0.015284  0.930258  0.394865
95 -0.390138 -0.643231 -1.168955
96  1.750394  0.253603  1.898755
97 -1.144264 -1.892648  0.095492
98  0.238605  1.738883  0.343062
99 -0.023853 -0.053403 -1.060967

[100 rows x 3 columns]

## DataFrame 끝

In [26]:
model.predict(z_d)

array([  30.68485439,   -0.36043804,   -2.99564207,   35.70131093,
         63.57196946, -115.45984035,   59.27573073,  131.04807062,
        160.16688366,   13.8570488 ,  117.20850091,   89.81033985,
         71.68704841,   -1.56735734,  135.13620325,    0.87758563,
         62.15346104,   31.24872245,   13.03693004,   20.27151664,
         56.44663194,   75.67607728,   69.75282484,   37.86651773,
        126.17321292,   73.48305012,  -11.83422223,  167.89436334,
         96.03105567,   31.78683962,   66.89107187,  156.92380936,
        102.77878311,    4.41683003,    1.15927073,    4.54820506,
         65.16789954,  162.0422677 ,   36.46526934,   28.11902163,
         90.17236905,  -81.87265314,  114.20148246,  140.82307743,
        109.30566321,   40.96707694,   69.04848407,   34.97132066,
         38.68460426,  123.5538472 ,  -49.17900253,   41.46717539,
         68.17550487,  165.67249774,  -36.40166558,   97.9691208 ,
         68.14486847,  175.39622957,   50.17407737,   46.78249

# 181210 

# 복습

In [49]:
n=10
x1=np.random.rand(n)
x2=np.random.rand(n)
x1

array([0.01391691, 0.78523896, 0.33952484, 0.26083092, 0.66314995,
       0.55184197, 0.4021745 , 0.66226447, 0.06283733, 0.79928983])

In [50]:
x=np.arange(12).reshape(4,3);x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [51]:
x[0:2],x[0]
# 첫번째 행부터 2-1행까지

(array([[0, 1, 2],
        [3, 4, 5]]), array([0, 1, 2]))

In [52]:
x=np.random.rand(4,2).round(2);x

array([[0.38, 0.57],
       [0.26, 0.08],
       [0.05, 0.54],
       [0.57, 0.67]])

In [53]:
type(x)

numpy.ndarray

In [54]:
df = pd.DataFrame(x)

In [55]:
df # 데이터프레임을 씌우면 이렇게 테이블로 나타남

0     1
0  0.38  0.57
1  0.26  0.08
2  0.05  0.54
3  0.57  0.67

In [56]:
df['새컬럼']=[1,2,3,4] #새컬럼이라는 새로운 열 추가하고 거기에 1,2,3,4를 넣는다
df


0     1  새컬럼
0  0.38  0.57    1
1  0.26  0.08    2
2  0.05  0.54    3
3  0.57  0.67    4

In [32]:
x=np.arange(12).reshape(4,3);x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [57]:
df.values

array([[0.38, 0.57, 1.  ],
       [0.26, 0.08, 2.  ],
       [0.05, 0.54, 3.  ],
       [0.57, 0.67, 4.  ]])

# 복습 끝